spring:
  application:
    name: gateway-zuul # 指定应用名称
server:
  port: 8050

eureka:
  instance:
    prefer-ip-address: true  # 是否显示主机的IP
  client:
    #配置eureka注册中心地址
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#      上线测试需要使用以下配置
      defaultZone: http://eureka-server:8761/eureka/
zuul:
  ignoredServices: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    order-service:
       path: /order-service/**
       serviceId: order-service
